export const gamesData = [
  {
    Name: "Nobunaga no Yabou DS",
    Platform: "DS",
    Year_of_Release: "2006",
    Genre: "Strategy",
    Publisher: "Tecmo Koei",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "1",
    Other_Sales: "0",
    Global_Sales: "1",
  },
  {
    Name: "God Eater Off Shot: Soma Shikkuzaru-hen Twin Pack & Animation Vol.4",
    Platform: "PS4",
    Year_of_Release: "2016",
    Genre: "Action",
    Publisher: "Namco Bandai Games",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "2",
    Other_Sales: "0",
    Global_Sales: "2",
  },
  {
    Name: "Cesar Millan's Dog Whisperer",
    Platform: "DS",
    Year_of_Release: "2008",
    Genre: "Simulation",
    Publisher: "Ubisoft",
    NA_Sales: "4",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "5",
    User_Score: "8.6",
    User_Count: "9",
    Developer: "Ubisoft",
  },
  {
    Name: "Super Mario Bros. 3",
    Platform: "GBA",
    Year_of_Release: "2003",
    Genre: "Platform",
    Publisher: "Nintendo",
    NA_Sales: "2.93",
    EU_Sales: "1.25",
    JP_Sales: "83",
    Other_Sales: "2",
    Global_Sales: "5.2",
  },
  {
    Name: "Pokemon Mystery Dungeon: Gates to Infinity",
    Platform: "3DS",
    Year_of_Release: "2012",
    Genre: "Role-Playing",
    Publisher: "Nintendo",
    NA_Sales: "44",
    EU_Sales: "29",
    JP_Sales: "47",
    Other_Sales: "7",
    Global_Sales: "1.27",
    Critic_Score: "59",
    Critic_Count: "46",
    User_Score: "6.3",
    User_Count: "134",
    Developer: '"Nintendo',
  },
  {
    Name: "Shark Tale",
    Platform: "PS2",
    Year_of_Release: "2004",
    Genre: "Action",
    Publisher: "Activision",
    NA_Sales: "37",
    EU_Sales: "29",
    JP_Sales: "0",
    Other_Sales: "1",
    Global_Sales: "75",
    Critic_Score: "69",
    Critic_Count: "30",
    User_Score: "6.5",
    User_Count: "6",
    Developer: "Edge of Reality",
  },
  {
    Name: "Cabela's Dangerous Hunts 2011",
    Platform: "X360",
    Year_of_Release: "2010",
    Genre: "Sports",
    Publisher: "Activision",
    NA_Sales: "28",
    EU_Sales: "1",
    JP_Sales: "0",
    Other_Sales: "2",
    Global_Sales: "32",
    Critic_Score: "55",
    Critic_Count: "7",
    Developer: "Activision",
  },
  {
    Name: "Putty Squad",
    Platform: "PSV",
    Year_of_Release: "2013",
    Genre: "Platform",
    Publisher: "System 3",
    NA_Sales: "1",
    EU_Sales: "1",
    JP_Sales: "0",
    Other_Sales: "1",
    Global_Sales: "3",
    User_Score: "8.2",
    User_Count: "6",
    Developer: "System 3",
  },
  {
    Name: "Bleach: Heat the Soul 6",
    Platform: "PSP",
    Year_of_Release: "2009",
    Genre: "Fighting",
    Publisher: "Sony Computer Entertainment",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "9",
    Other_Sales: "0",
    Global_Sales: "9",
  },
  {
    Name: "Dragon Ball: Raging Blast",
    Platform: "X360",
    Year_of_Release: "2009",
    Genre: "Fighting",
    Publisher: "Namco Bandai Games",
    NA_Sales: "36",
    EU_Sales: "8",
    JP_Sales: "2",
    Other_Sales: "4",
    Global_Sales: "51",
    Critic_Score: "56",
    Critic_Count: "29",
    User_Score: "7.5",
    User_Count: "33",
    Developer: "Spike",
  },
  {
    Name: "Pitfall!",
    Platform: "2600",
    Year_of_Release: "1981",
    Genre: "Platform",
    Publisher: "Activision",
    NA_Sales: "4.21",
    EU_Sales: "24",
    JP_Sales: "0",
    Other_Sales: "5",
    Global_Sales: "4.5",
  },
  {
    Name: "The Godfather: Dons Edition",
    Platform: "PS3",
    Year_of_Release: "2007",
    Genre: "Action",
    Publisher: "Electronic Arts",
    NA_Sales: "25",
    EU_Sales: "2",
    JP_Sales: "0",
    Other_Sales: "3",
    Global_Sales: "29",
  },
  {
    Name: "World Snooker Championship 2007",
    Platform: "PS3",
    Year_of_Release: "2007",
    Genre: "Sports",
    Publisher: "Sega",
    NA_Sales: "0",
    EU_Sales: "1",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "1",
  },
  {
    Name: "The Croods: Prehistoric Party!",
    Platform: "DS",
    Year_of_Release: "2013",
    Genre: "Misc",
    Publisher: "D3Publisher",
    NA_Sales: "3",
    EU_Sales: "4",
    JP_Sales: "0",
    Other_Sales: "1",
    Global_Sales: "7",
  },
  {
    Name: "NBA Live 06",
    Platform: "GC",
    Year_of_Release: "2005",
    Genre: "Sports",
    Publisher: "Electronic Arts",
    NA_Sales: "25",
    EU_Sales: "7",
    JP_Sales: "0",
    Other_Sales: "1",
    Global_Sales: "33",
    Critic_Score: "76",
    Critic_Count: "14",
    Developer: "EA Canada",
  },
  {
    Name: "Touch Detective (JP sales)",
    Platform: "DS",
    Year_of_Release: "2006",
    Genre: "Adventure",
    Publisher: "505 Games",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "2",
    Other_Sales: "0",
    Global_Sales: "2",
  },
  {
    Name: "Memories Off: Sorekara Again",
    Platform: "PS2",
    Year_of_Release: "2006",
    Genre: "Adventure",
    Publisher: "KID",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "2",
    Other_Sales: "0",
    Global_Sales: "2",
  },
  {
    Name: "Lionel Trains: On Track",
    Platform: "DS",
    Year_of_Release: "2006",
    Genre: "Action",
    Publisher: "DSI Games",
    NA_Sales: "4",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "4",
    Critic_Score: "47",
    Critic_Count: "4",
    Developer: "Black Lantern Studios",
  },
  {
    Name: "Godzilla Unleashed: Double Smash",
    Platform: "DS",
    Year_of_Release: "2007",
    Genre: "Action",
    Publisher: "Atari",
    NA_Sales: "11",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "1",
    Global_Sales: "12",
    Critic_Score: "28",
    Critic_Count: "18",
    User_Score: "4.9",
    User_Count: "8",
    Developer: "Santa Cruz Games",
  },
  {
    Name: "Agatha Christie: Evil Under the Sun",
    Platform: "Wii",
    Year_of_Release: "2008",
    Genre: "Adventure",
    Publisher: "The Adventure Company",
    NA_Sales: "6",
    EU_Sales: "1",
    JP_Sales: "0",
    Other_Sales: "1",
    Global_Sales: "8",
    Critic_Score: "46",
    Critic_Count: "6",
    User_Score: "7.3",
    User_Count: "6",
    Developer: "AWE Games",
  },
  {
    Name: "Rogue Trip: Vacation 2012",
    Platform: "PS",
    Year_of_Release: "1998",
    Genre: "Racing",
    Publisher: "GT Interactive",
    NA_Sales: "21",
    EU_Sales: "14",
    JP_Sales: "0",
    Other_Sales: "2",
    Global_Sales: "38",
  },
  {
    Name: "Parfait",
    Platform: "PSV",
    Year_of_Release: "2015",
    Genre: "Adventure",
    Publisher: "TGL",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "3",
    Other_Sales: "0",
    Global_Sales: "3",
  },
  {
    Name: "Fairy Tail: Zelef Kakusei",
    Platform: "PSP",
    Year_of_Release: "2012",
    Genre: "Action",
    Publisher: "Unknown",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "7",
    Other_Sales: "0",
    Global_Sales: "7",
  },
  {
    Name: "3D Baseball",
    Platform: "PS",
    Year_of_Release: "1996",
    Genre: "Sports",
    Publisher: "BMG Interactive Entertainment",
    NA_Sales: "2",
    EU_Sales: "1",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "3",
  },
  {
    Name: "The Guided Fate Paradox",
    Platform: "PS3",
    Year_of_Release: "2013",
    Genre: "Role-Playing",
    Publisher: "Nippon Ichi Software",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "6",
    Other_Sales: "0",
    Global_Sales: "7",
    Critic_Score: "74",
    Critic_Count: "27",
    User_Score: "7.8",
    User_Count: "66",
    Developer: "Nippon Ichi Software",
  },
  {
    Name: "Midway Arcade Treasures",
    Platform: "PS2",
    Year_of_Release: "2003",
    Genre: "Misc",
    Publisher: "Midway Games",
    NA_Sales: "72",
    EU_Sales: "56",
    JP_Sales: "0",
    Other_Sales: "19",
    Global_Sales: "1.46",
    Critic_Score: "76",
    Critic_Count: "22",
    Developer: "Midway",
  },
  {
    Name: "NHL 06",
    Platform: "XB",
    Year_of_Release: "2005",
    Genre: "Sports",
    Publisher: "Electronic Arts",
    NA_Sales: "19",
    EU_Sales: "5",
    JP_Sales: "0",
    Other_Sales: "1",
    Global_Sales: "25",
    Critic_Score: "79",
    Critic_Count: "35",
    User_Score: "8.4",
    User_Count: "18",
    Developer: "EA Canada",
  },
  {
    Name: "Monster High: Ghoul Spirit",
    Platform: "Wii",
    Year_of_Release: "2011",
    Genre: "Misc",
    Publisher: "THQ",
    NA_Sales: "42",
    EU_Sales: "7",
    JP_Sales: "0",
    Other_Sales: "4",
    Global_Sales: "53",
    Developer: "THQ",
  },
  {
    Name: "Monster Hunter Frontier Online: Forward 2",
    Platform: "X360",
    Year_of_Release: "2011",
    Genre: "Role-Playing",
    Publisher: "Capcom",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "3",
    Other_Sales: "0",
    Global_Sales: "3",
  },
  {
    Name: "Stunt GP",
    Platform: "PS2",
    Year_of_Release: "2001",
    Genre: "Racing",
    Publisher: "Titus",
    NA_Sales: "2",
    EU_Sales: "2",
    JP_Sales: "0",
    Other_Sales: "1",
    Global_Sales: "5",
    Critic_Score: "49",
    Critic_Count: "8",
    User_Score: "8.1",
    User_Count: "9",
    Developer: "Team 17",
  },
  {
    Name: "American Girl: Julie Finds a Way",
    Platform: "DS",
    Year_of_Release: "2007",
    Genre: "Adventure",
    Publisher: "THQ",
    NA_Sales: "1",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "1",
    Global_Sales: "1",
    Developer: "Webfoot Technologies",
  },
  {
    Name: "Hakuouki: Reimeiroku",
    Platform: "PS2",
    Year_of_Release: "2010",
    Genre: "Adventure",
    Publisher: "Idea Factory",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "5",
    Other_Sales: "0",
    Global_Sales: "5",
  },
  {
    Name: "The Book of Unwritten Tales",
    Platform: "PC",
    Year_of_Release: "2009",
    Genre: "Adventure",
    Publisher: "HMH Interactive",
    NA_Sales: "0",
    EU_Sales: "8",
    JP_Sales: "0",
    Other_Sales: "2",
    Global_Sales: "1",
    Critic_Score: "82",
    Critic_Count: "32",
    User_Score: "8.2",
    User_Count: "144",
    Developer: "KING Art",
  },
  {
    Name: "Madagascar",
    Platform: "PS2",
    Year_of_Release: "2005",
    Genre: "Platform",
    Publisher: "Activision",
    NA_Sales: "78",
    EU_Sales: "45",
    JP_Sales: "0",
    Other_Sales: "7",
    Global_Sales: "1.31",
    Critic_Score: "69",
    Critic_Count: "25",
    User_Score: "7.4",
    User_Count: "25",
    Developer: "Toys for Bob",
  },
  {
    Name: "Metal Slug Anthology",
    Platform: "PSP",
    Year_of_Release: "2007",
    Genre: "Shooter",
    Publisher: "Ignition Entertainment",
    NA_Sales: "2",
    EU_Sales: "0",
    JP_Sales: "2",
    Other_Sales: "1",
    Global_Sales: "5",
    Critic_Score: "78",
    Critic_Count: "26",
    User_Score: "7.4",
    User_Count: "25",
    Developer: "Terminal Reality",
  },
  {
    Name: "The Price is Right",
    Platform: "DS",
    Year_of_Release: "2008",
    Genre: "Misc",
    Publisher: "Ubisoft",
    NA_Sales: "46",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "4",
    Global_Sales: "49",
    Developer: "Ludia Inc.",
  },
  {
    Name: "Disney's Brother Bear",
    Platform: "GBA",
    Year_of_Release: "2003",
    Genre: "Action",
    Publisher: "THQ",
    NA_Sales: "28",
    EU_Sales: "1",
    JP_Sales: "0",
    Other_Sales: "1",
    Global_Sales: "39",
    Developer: "Vicarious Visions",
  },
  {
    Name: "Re-Volt",
    Platform: "N64",
    Year_of_Release: "1999",
    Genre: "Racing",
    Publisher: "Acclaim Entertainment",
    NA_Sales: "14",
    EU_Sales: "4",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "18",
  },
  {
    Name: "Teenage Mutant Ninja Turtles 3: Mutant Nightmare",
    Platform: "DS",
    Year_of_Release: "2005",
    Genre: "Action",
    Publisher: "Konami Digital Entertainment",
    NA_Sales: "5",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "6",
    Critic_Score: "58",
    Critic_Count: "10",
    User_Score: "7",
    User_Count: "5",
    Developer: "Konami",
  },
  {
    Name: "Kabushiki Baibai Trainer: Kabutore!",
    Platform: "DS",
    Year_of_Release: "2006",
    Genre: "Simulation",
    Publisher: "Konami Digital Entertainment",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "1",
    Other_Sales: "0",
    Global_Sales: "1",
  },
  {
    Name: "Star Driver: Kagayaki no Takuto - Ginga Bishounen Densetsu",
    Platform: "PSP",
    Year_of_Release: "2011",
    Genre: "Adventure",
    Publisher: "Namco Bandai Games",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "5",
    Other_Sales: "0",
    Global_Sales: "5",
  },
  {
    Name: "Colony Wars",
    Platform: "PS",
    Year_of_Release: "1997",
    Genre: "Simulation",
    Publisher: "Psygnosis",
    NA_Sales: "24",
    EU_Sales: "16",
    JP_Sales: "0",
    Other_Sales: "3",
    Global_Sales: "42",
    Critic_Score: "91",
    Critic_Count: "12",
    User_Score: "7.8",
    User_Count: "12",
    Developer: "Psygnosis",
  },
  {
    Name: "Battle of Giants: Dragons",
    Platform: "DS",
    Year_of_Release: "2009",
    Genre: "Strategy",
    Publisher: "Ubisoft",
    NA_Sales: "3",
    EU_Sales: "25",
    JP_Sales: "0",
    Other_Sales: "6",
    Global_Sales: "62",
    User_Score: "6",
    User_Count: "4",
    Developer: "Ubisoft Quebec",
  },
  {
    Name: "NFL Fever 2003",
    Platform: "XB",
    Year_of_Release: "2002",
    Genre: "Sports",
    Publisher: "Microsoft Game Studios",
    NA_Sales: "46",
    EU_Sales: "13",
    JP_Sales: "0",
    Other_Sales: "2",
    Global_Sales: "61",
    Critic_Score: "72",
    Critic_Count: "25",
    User_Score: "8.6",
    User_Count: "12",
    Developer: "Microsoft Game Studios",
  },
  {
    Name: "Rayman",
    Platform: "PS",
    Year_of_Release: "1995",
    Genre: "Platform",
    Publisher: "Ubisoft",
    NA_Sales: "1.54",
    EU_Sales: "1.33",
    JP_Sales: "0",
    Other_Sales: "16",
    Global_Sales: "3.03",
  },
  {
    Name: "Little League World Series Baseball: Double Play",
    Platform: "DS",
    Year_of_Release: "2010",
    Genre: "Sports",
    Publisher: "Activision",
    NA_Sales: "7",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "1",
    Global_Sales: "7",
    Developer: "Activision",
  },
  {
    Name: "GTR Evolution",
    Platform: "PC",
    Year_of_Release: "2008",
    Genre: "Racing",
    Publisher: "Atari",
    NA_Sales: "0",
    EU_Sales: "2",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "3",
    Critic_Score: "83",
    Critic_Count: "19",
    User_Score: "8.2",
    User_Count: "63",
    Developer: "SimBin",
  },
  {
    Name: "MTX Mototrax",
    Platform: "PSP",
    Year_of_Release: "2006",
    Genre: "Racing",
    Publisher: "Activision",
    NA_Sales: "4",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "5",
    Critic_Score: "67",
    Critic_Count: "8",
    Developer: "Left Field Productions",
  },
  {
    Name: "Sonic Heroes",
    Platform: "XB",
    Year_of_Release: "2003",
    Genre: "Platform",
    Publisher: "Sega",
    NA_Sales: "41",
    EU_Sales: "43",
    JP_Sales: "1",
    Other_Sales: "5",
    Global_Sales: "9",
    Critic_Score: "73",
    Critic_Count: "28",
    User_Score: "7.6",
    User_Count: "34",
    Developer: "Sonic Team",
  },
  {
    Name: "Madden NFL 10",
    Platform: "X360",
    Year_of_Release: "2009",
    Genre: "Sports",
    Publisher: "Electronic Arts",
    NA_Sales: "2.52",
    EU_Sales: "9",
    JP_Sales: "0",
    Other_Sales: "22",
    Global_Sales: "2.83",
    Critic_Score: "85",
    Critic_Count: "58",
    User_Score: "6.1",
    User_Count: "90",
    Developer: "EA Tiburon",
  },
];
